version: '3'

services:
  mariadb:
    networks: 
      - inception
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file: .env
    restart: on-failure

  wordpress:
    networks:
      - inception
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/
    expose:
      - "9000"
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    networks:
      - inception
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure
    depends_on: 
      - wordpress
  
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mportrai/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mportrai/data/mariadb"

networks:
  inception:
    driver: bridge