version: '3'

services:
  mariadb:
    networks: 
      - inception
    image: mariadb
    container_name: mariadb
    build:
      context: ./bonus/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file: .env
    restart: on-failure

  wordpress:
    networks:
      - inception
    image: wordpress
    container_name: wordpress
    build:
      context: ./bonus/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/
    expose:
      - "9000"
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    networks:
      - inception
    image: nginx
    container_name: nginx
    build:
      context: ./bonus/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure
    depends_on: 
      - wordpress
  
  adminer:
    networks:
      - inception
    image: adminer
    container_name: adminer
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    environment:
      - ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - "8080:8080"
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb
  
  # redis:
  #   networks:
  #     - inception
  #   image: redis
  #   container_name: redis
  #   build:
  #     context: ./bonus/redis_cache
  #     dockerfile: Dockerfile
  #   volumes: 
  #     - wordpress:/var/www/html/
  #   ports:
  #     - "6379:6379"
  #   env_file: .env
  #   restart: on-failure
  #   depends_on:
  #     - wordpress

  # ftp-server:
  #   networks:
  #     - inception
  #   image: ftp-server
  #   container_name: ftp-server
  #   build:
  #     context: ./bonus/ftp-server
  #     dockerfile: Dockerfile
  #   volumes: 
  #     - wordpress:/var/ftp
  #   ports:
  #     - "21:21"
  #   env_file: .env
  #   restart: on-failure
  #   depends_on:
  #     - wordpress

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mportrai/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mportrai/data/mariadb"

networks:
  inception:
    driver: bridge